name: Build HTML and PDF documentation

on:
  push:
    branches:
      - setup-workflows
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # checkout specific branch
        ref: setup-workflows

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Sphinx HTML
      run: make html

    - name: Upload zip to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: build/html

    - name: Build Sphinx latex file
      run: make latex

    # - name: Compile pdf from tex
    #   uses: xu-cheng/latex-action@v3
    #   with:
    #     root_file: timetaggermodulesuserguide.tex
    #     working_directory: build/latex
    #     compiler: lualatex
    #     pre_compile: "tlmgr update --self && tlmgr update --all"
    #     args: -lualatex -file-line-error -interaction=nonstopmode
    - name: complie pdf using texlive-action
      uses: xu-cheng/texlive-action@v2
      with:
        scheme: small
        run: |
          tlmgr update --self
          tlmgr update --all
          tlmgr install fncychap
          make -C build/latex



    - name: upload log if latexmk fails
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: latex_files
        path: |
          build/latex/*


    - name: Upload pdf to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: build/latex/timetaggermodulesuserguide.pdf
