name: Build and publish documentation

on:
  release:
    types:
      - created

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        # checkout specific branch
        ref: main

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
      with:
        enable-cache: true
        version: latest

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --frozen --no-dev

    - name: Build project
      run: |
        make html
        make latex

    - name: Compile PDF
      uses: xu-cheng/latex-action@v4
      with:
        root_file: timetaggermodulesintegrationguide.tex
        latexmk_use_lualatex: true
        working_directory: build/latex
        pre_compile: "tlmgr update --self && tlmgr update --all"

    - name: Upload log if latexmk fails
      if: ${{ failure() }}
      uses: actions/upload-artifact@v7
      with:
        name: latex_files
        path: |
          build/latex/*

    - name: Rename PDF
      run: |
        mv build/latex/timetaggermodulesintegrationguide.pdf build/latex/TimeTagger_Module_Integration_Guide.pdf

    - name: Publish HTML
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: ./build/html/*
        target: ${{ secrets.TARGETHTML }}
        strip_components: 2
        rm: true

    - name: Publish PDF
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: ./build/latex/TimeTagger_Module_Integration_Guide.pdf
        target: ${{ secrets.TARGETPDF }}
        strip_components: 3
        rm: true
